apiVersion: v2
type: application
name: nidhogg
description: A chart that deploys argo-cd and the Yggdrasil chart.
version: v0.3.8

dependencies:
  - name: argo-cd
    version: "2.17.1"
    repository: "https://argoproj.github.io/argo-helm"
  - name: mukube-vnet
    version: "v0.1.2"
    repository: "https://distributed-technologies.github.io/helm-repository/"
    condition: 'installCNI'
